map_server:
  ros__parameters:
    map_topic: nav_lite/map
    map_frame: odom
    base_link_frame: base_link

# List of sensors
    sensors: [ sensor0, sensor1, sensor2 ]

    sensor0:
        topic: lidar/range
        device:
            type: Garmin LIdar Lite
            addr: 0x62
            timeout: 60000
        transform:
            frame: base_lidar
            posX: 0.075
            posY: 0.00
            posZ: -0.040
            roll: 0.0
            pitch: 0.0
            yaw: 0.0
    sensor1:
        topic: vl53l1x/range
        device:
            type: vl53l1x
            addr: 0x29
            timeout: 60000
        transform:
            frame: base_down
            posX: 0.01
            posY: -0.06
            posZ: -0.055
            roll: 0.0
            pitch: deg(270)  # straight down
            yaw: 0.0
    sensor2:
        topic: sonar/range
        device:
            type: GY-US42
            addr: 0x70
            timeout: 60000
        transform:
            frame: base_up
            posX: -0.01
            posY: -0.045
            posZ: -0.01
            roll: 0.0
            pitch: deg(90)  # Straight up I think
            yaw: 0.0
            

